import pandas as pd 
import numpy as np
import sys
from Bio import SeqIO
from Bio import SeqRecord
from Bio.Seq import Seq
from read_bionano import read_key,read_cut


def extract_seq(seq_record, ID):
    for i in range(len(seq_record)):
        if seq_record[i].id == str(ID):
            return seq_record[i]
    
def cut_seq(cut,seq_record_total):
    cut_records = []    
    for j in cut.index:
        cut_ID = extract_seq(seq_record_total, cut.loc[j,'Sequence_ID'])
        modified_seq_ID = SeqRecord.SeqRecord(Seq(str(cut_ID.seq[int(cut.loc[j,'oldStart']):int(cut.loc[j,'oldEnd'])])),str(cut.loc[j,'newId']),description="")
        cut_records.append(modified_seq_ID)
    return cut_records 

def main(input_fasta_file,key_file,cut_NGS_coord_file,output_cut_fasta_file):
    input_precut = list(SeqIO.parse(input_fasta_file, "fasta"))
    keys = read_key(key_file)       
    cut_coord = read_cut(cut_NGS_coord_file,keys)
    cut_fa = cut_seq(cut_coord,input_precut)
    cut_fa.sort(key=lambda r:int(r.id))
    SeqIO.write(cut_fa, output_cut_fasta_file, "fasta")


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Cut fasta files based on conflict junction coordinates on cmap level')
    parser.add_argument('-i','--input_fasta_file', required=True,
                        help='Input fasta file to be cut')
    parser.add_argument('-k','--key_file', required=True,
                        help='Key file of input fasta generated by fa2cmap_multi_color.pl, named _CTTAAG_0kb_0labels_key.txt')
    parser.add_argument('-c','--cut_NGS_coord_file',required=True,
                        help='auto_cut_NGS_coord_translation.txt file in directory cut_conflicts, generated by cut_conflict.pl')
    parser.add_argument('-o','--output_cut_fasta_file', default='cut.fasta',
                        help='output fasta file with conflict resolved on the sequence level')
    args = parser.parse_args()
    main(input_fasta_file=args.input_fasta_file, key_file=args.key_file,cut_NGS_coord_file=args.cut_NGS_coord_file, output_cut_fasta_file=args.output_cut_fasta_file)

